name: qr_contacts
description: Share your contacts as QR codes
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.17
  flutter_contacts: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  icons_launcher: "^2.1.0"

icons_launcher:
  image_path: "assets/qrcontacts_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true
    web:
      enable: true

flutter:
  uses-material-design: true
